### ISSUE TITLE
换了4个节点，都验证不了

### ISSUE THREAD

**Issue by anonymouscnuser** [tg-watchdog/tg-watchdog#39]
包括3家机场。
虽然不知道您机器人是怎么实现的，但我怀疑一下你网炸了

![image](https://user-images.githubusercontent.com/68681806/236645635-a253b685-8d10-43b0-865e-7263c07594cb.png)

**Comment by Astrian** [comment]
思考，个人合理怀疑是 Cloudflare 服务出现了一些故障，换个时间试试看呢？

**Comment by anonymouscnuser** [comment]
Work well on my Android phone, but failed on PC (win 10).

**Comment by Astrian** [comment]
> Work well on my Android phone, but failed on PC (win 10).

思考，我研究一下，感谢你的反馈
